################################################################################
# Flex Radio Services
################################################################################
# docker-compose -f docker-compose.yml up -d
# .env file required with value for HOSTNAME for traefik
# This is for running in a container with a traefik setup
################################################################################

services:
  flex-radio-services:
    image: ghcr.io/jeffu231/flexradioservices:latest
    container_name: flex-radio-api
    restart: unless-stopped
    ports:
      - "4991-4992:4991-4992/udp" # Ports for radio communication
      - "6005-6020:6005-6020/tcp" # Range of CAT ports defined in appsettings
    networks:
      - traefik-net
    volumes:
      - flex-radio-api-settings:/app/appsettings
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flex-radio-services-api.rule=Host(`$HOSTNAME`) && (PathPrefix(`/api/frs/`))"
      - "traefik.http.services.flex-radio-services-api.loadbalancer.server.port=8080"

networks:
  traefik-net:
    external: true

volumes:
  flex-radio-api-settings:
    external: true
