################################################################################
# Flex Radio Services
################################################################################
# Use in conjunction with docker-compose.yml for local development
# .env file required with values for GITHUB_USERNAME and GITHUB_TOKEN for Github 
#      nuget repository read access
################################################################################
# docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d
################################################################################

services:
  flex-radio-services:
    image: flex-radio-api-dev
    container_name: flex-radio-api-dev
    build: 
      context: .
      dockerfile: FlexRadioServices/Dockerfile
      args:
        - GITHUB_USERNAME=${GITHUB_USERNAME}
        - GITHUB_TOKEN=${GITHUB_TOKEN}