################################################################################
# Flex Radio Services
################################################################################
# docker-compose -f docker-compose.yml -p flex-radio-services up
# .env file required with values for GITHUB_USERNAME and GITHUB_TOKEN for Github 
#      nuget repository read access
################################################################################

services:
  flex-radio-services:
    image: flex-radio-api
    restart: unless-stopped
    build: 
      context: .
      dockerfile: FlexRadioServices/Dockerfile
      args:
        - GITHUB_USERNAME=${GITHUB_USERNAME}
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    ports:
      - "4991-4992:4991-4992/udp"
      - "6005-6020:6005-6020/tcp"
      
    

