################################################################################
# Flex Radio Services
################################################################################
# docker-compose -f docker-compose.yml -p flex-radio-services up -d
# .env file required with values for GITHUB_USERNAME and GITHUB_TOKEN for Github 
#      nuget repository read access
# This is for running locally without a traefik setup
################################################################################
version: "3.7"

services:
  flex-radio-services:
    image: flex-radio-api
    restart: unless-stopped
    ports:
      - "4991-4992:4991-4992/udp"
      - "6005-6020:6005-6020/tcp"
    networks:
      - traefik-net
    build: 
      context: https://github.com/jeffu231/FlexRadioServices.git
      dockerfile: FlexRadioServices/Dockerfile
      args:
        - GITHUB_USERNAME=${GITHUB_USERNAME}
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flex-radio-services-api.rule=Host(`docker01.home.kb9kld.org`) && (PathPrefix(`/api/frs/`))"

networks:
  traefik-net:
    external: true