################################################################################
# Flex Radio Services
################################################################################
# docker-compose -f docker-compose.yml -f docker-compose-dev.yml -p flex-radio-services up -d 
# .env file required with values for GITHUB_USERNAME and GITHUB_TOKEN for Github 
#      nuget repository read access
################################################################################

services:
  flex-radio-services:
    image: flex-radio-api-dev
    build: 
      context: .
      dockerfile: FlexRadioServices/Dockerfile
      args:
        - GITHUB_USERNAME=${GITHUB_USERNAME}
        - GITHUB_TOKEN=${GITHUB_TOKEN}