################################################################################
# Flex Radio Services
################################################################################
# docker-compose -f docker-compose.yml -f docker-compose-dev.yml -p flex-radio-services up -d 
# .env file required with values for GITHUB_USERNAME and GITHUB_TOKEN for Github 
#      nuget repository read access
################################################################################
version: "3.7"

services:
  flex-radio-services:
    build: 
      context: .
